const items = [
    {
        id: '001',
        image: 'images/puma2.jpeg',
        company: 'PUMA',
        item_name: 'Rebound LayUp SL High Tops For Men  (White)',
        _price: 4999,
        current_price: 2184,
        discount_percentage: 56,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.9,
            count: 1900,
        },
    },
    {
        id: '002',
        image: 'images/puma3.jpeg',
        company: 'PUMA',
        item_name: 'Puma Smash v2 L Sneakers For Men  (White)',
        _price: 4999,
        current_price: 2158,
        discount_percentage: 56,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: 'images/puma.jpeg',
        company: 'PUMA',
        item_name: 'X-Ray 2 Square Sneakers For Men  (Blue)',
        _price: 6999,
        current_price: 3231,
        discount_percentage: 53,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: 'images/puma4.jpeg',
        company: 'PUMA',
        item_name: 'Supertec Running Shoes For Men  (Blue)',
        _price: 6999,
        current_price: 3943,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: 'images/puma5.jpeg',
        company: 'PUMA',
        item_name: ' Running Shoes For Men  (Blue)',
        _price: 5000,
        current_price: 2500,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: 'images/puma6.jpeg',
        company: 'PUMA',
        item_name: 'X-Ray 2 Square Sneakers For Men  (Black)',
        _price: 6999,
        current_price: 3948,
        discount_percentage: 43,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 5.0,
            count: 100,
        },
    },
    {
        id: '007',
        image: 'images/puma7.jpeg',
        company: 'PUMA',
        item_name: 'Bridge Comfort Running Shoes For Men  (Grey)',
        _price: 2499,
        current_price: 1376,
        discount_percentage: 45,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: 'images/puma8.jpeg',
        company: 'PUMA',
        item_name: 'ST Runner v3 Mesh Running Shoes For Men  (Black)',
        _price: 4499,
        current_price: 2156,
        discount_percentage: 52,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    },
    {
        id: '009',
        image: 'images/puma.jpeg',
        company: 'PUMA',
        item_name: 'Bridge Comfort Running Shoes For Men  (Black)',
        _price: 2499,
        current_price: 1299,
        discount_percentage: 48,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.8,
            count: 200,
        },
    },
    {
        id: '010',
        image: 'images/new9.jpeg',
        company: 'New Balance',
        item_name: '1080 Running Shoes For Men  (Green)',
        _price: 4999,
        current_price: 2867,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.1,
            count: 3455,
        },
    },
    {
        id: '011',
        image: 'images/new10.jpeg',
        company: 'New Balance',
        item_name: '490 Running Shoes For Men  (Grey)',
        _price: 19999,
        current_price: 9899,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.9,
            count: 34576,
        },
    },
    {
        id: '012',
        image: 'images/puma9.jpeg',
        company: 'New Balance',
        item_name: 'Bridge Comfort Running Shoes For Men  (White)',
        _price: 2499,
        current_price: 1631,
        discount_percentage: 34,
        return_period: 14,
        delivery_date: '10 Jan 2024',
        rating: {
            stars: 4.7,
            count: 3537,
        },
    }
];